#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Projects -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    # If no TMUX session is running, create a new one
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if tmux has-session -t="$selected_name" 2>/dev/null; then
    # If the session already exists, attach to it
    if [[ -n $TMUX ]]; then
        # If already inside TMUX, switch to the session
        tmux switch-client -t "$selected_name"
    else
        # If not inside TMUX, attach to the session
        tmux attach-session -t "$selected_name"
    fi
else
    # Create a new session if it doesn't exist
    tmux new-session -ds "$selected_name" -c "$selected"
    if [[ -n $TMUX ]]; then
        tmux switch-client -t "$selected_name"
    else
        tmux attach-session -t "$selected_name"
    fi
fi
