#! /bin/sh

xrandr --output $(xrandr | grep ' connected' | awk '{print $1}' | head -n 1) --scale 0.75x0.75
setxkbmap -option "caps:swapescape" &
pgrep -x sxhkd >/dev/null || sxhkd &
nm-applet &
pgrep -x $HOME/.config/lemonbar/panel >/dev/null || $HOME/.config/lemonbar/panel &
killall redshift
redshift &
feh --no-fehbg --bg-fill '/home/pebbles/Pictures/eva-wall.jpg' &
pgrep -x picom >/dev/null || picom &
pgrep -x $HOME/.config/bspwm/scripts/fullscreen_toggle >/dev/null || $HOME/.config/bspwm/scripts/fullscreen_toggle &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.5
bspc config pointer_modifier mod1
bspc config normal_border_color "#61677a"
bspc config active_border_color "#88C0D0"
bspc config focused_border_color "#88C0D0"

bspc rule -a "*:Toolkit:Picture-in-Picture" state=floating sticky=on focus=on rectangle=400x200+1015+60
bspc rule -a Pavucontrol state=floating
bspc rule -a Sxiv state=floating rectangle=800x500+0+0 center=true
bspc rule -a mpv state=floating rectangle=400x400+1015+60
