#! /bin/sh

xrandr --output $(xrandr | grep ' connected' | awk '{print $1}' | head -n 1) --scale 0.75x0.75
redshift &
# setxkbmap -option "caps:swapescape" &
pgrep -x sxhkd >/dev/null || sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh &
feh --no-fehbg --bg-max '/home/pebbles/Pictures/gravity.webp' &
picom -b &
$HOME/.config/bspwm/scripts/fullscreen_toggle &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.5
bspc config pointer_modifier mod1
bspc config normal_border_color "#61677a"
bspc config active_border_color "#cdd6f4"
bspc config focused_border_color "#cdd6f4"

bspc rule -a "*:Toolkit:Picture-in-Picture" \
    state=floating sticky=on follow=off focus=on \
    rectangle=400x200+1010+60
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Mumble state=floating follow=on
bspc rule -a Xviewer state=floating follow=on rectangle=800x600+0+0 center=true
bspc rule -a Io.github.celluloid_player.Celluloid state=floating follow=on rectangle=400x400+1010+60
