#!/bin/sh

TEMPDIR=~/.cache/thumbnails
draw() {
    if [ -n "$TMUX" ]; then
        y=3
    else
        y=2
    fi
    path="$(readlink -f -- "$1" | sed 's/\\/\\\\/g;s/"/\\"/g')"
    printf '{"action":"add","identifier":"preview","x":%d,"y":%d,"width":%d,"height":%d,"scaler":"contain","scaling_position_x":0.5,"scaling_position_y":0.5,"path":"%s"}\n' \
        "$x" "$y" "$w" "$h" "$path" >"$FIFO_UEBERZUG"
    exit 1
}

hash() {
    cache="$TEMPDIR/$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f -- "$1")" | sha256sum | cut -d' ' -f1).jpg"
}

cache() {
    if ! [ -f "$cache" ]; then
        dir="$(dirname -- "$cache")"
        [ -d "$dir" ] || mkdir -p -- "$dir"
        "$@"
    fi
    draw "$cache"
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(basename "$file" | tr '[A-Z]' '[a-z]')" in
*.tgz | *.tar.gz) tar tzf "$file" ;;
*.tar.bz2 | *.tbz2) tar tjf "$file" ;;
*.tar.txz | *.txz) xz --list "$file" ;;
*.tar) tar tf "$file" ;;
*.zip | *.jar | *.war | *.ear | *.oxt) unzip -Z1 "$file" ;;
*.rar) unrar l "$file" ;;
*.7z) 7z l "$file" ;;
*.[1-8]) man "$file" | col -b ;;
*.o) nm "$file" ;;
*.odt | *.ods | *.odp | *.sxw) odt2txt "$file" ;;
*.doc) catdoc "$file" ;;
*.docx) docx2txt "$file" ;;
*.xls | *.xlsx)
    ssconvert --export-type=Gnumeric_stf:stf_csv "$file" "fd://1" | batcat --paging=never --terminal-width="$w" --color=always --theme=Nord --language=csv
    ;;
*.iso) isoinfo -d -i "$file" ;;
*.wav | *.mp3 | *.flac | *.m4a | *.wma | *.ape | *.ac3 | *.og[agx] | *.spx | *.opus | *.as[fx] | *.mka)
    mediainfo "$file"
    ;;
*.avi | *.mp4 | *.wmv | *.dat | *.3gp | *.ogv | *.mkv | *.mpg | *.mpeg | *.vob | *.fl[icv] | *.m2v | *.mov | *.webm | *.ts | *.mts | *.m4v | *.r[am] | *.qt | *.divx)
    if [ -n "$FIFO_UEBERZUG" ]; then
        hash "$file"
        cache ffmpegthumbnailer -i "$file" -o "$cache" -s 0
    fi
    ;;
*.pdf)
    if [ -n "$FIFO_UEBERZUG" ]; then
        hash "$file"
        cache gs -o "$cache" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
    fi
    ;;
*.bmp | *.jpg | *.jpeg | *.png | *.xpm | *.webp | *.gif | *.jfif)
    if [ -n "$FIFO_UEBERZUG" ]; then
        draw "$file"
    fi
    ;;
*.svg)
    if [ -n "$FIFO_UEBERZUG" ]; then
        hash "$file"
        cache convert "$file" "$cache"
    fi
    ;;
*)
    batcat --paging=never --terminal-width="$w" --color=always --theme=Nord "$file"
    ;;
esac
file -Lb -- "$file" | fold -s -w "$width"
return 127
