format = """
[┌─]()\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
\n[└─]()\
"""

[username]
show_always = true
style_user = "fg:#fff6e0"
format = '\[[$user]($style)\]-'

[directory]
format = '\[[$path]($style)\]'
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󱔗 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "
"Projects" = "󰨸 "
"Notes" = "󰸕 "
"Github" = " "

[git_branch]
format = '-\[[$symbol$branch]($style)\]'

[git_status]
format = '-\[[$all_status$ahead_behind]($style)\]'
