format = """
[┌─](fg:black)\
[$directory](fg:black)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
\n[└─](fg:black)\
"""

[directory]
format = '\[[$path]($style)\]'
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = '[ $branch ]($style)'

[git_status]
format = '[$all_status$ahead_behind]($style)'
