format = """
[┌─](fg:black)\
[$directory](fg:black)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
\n[└─](fg:black)\
"""

[directory]
format = '\[[$path]($style)\](fg:black) '
read_only = " ro"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[git_branch]
symbol = ""

