#!/bin/sh

# creating nessesery folders
mkdir -p Github/ Projects/

# installing nala
sudo apt install nala -y

# installing generic packages
sudo nala install -y dunst alacritty ripgrep xclip python3.12-venv rofi bspwm sxhkd feh lf bat mediainfo catdoc docx2txt odt2txt ffmpegthumbnailer imagemagick mpv sxiv evince file-roller redshift tmux scrot brightnessctl zoxide fd-find lxappearance htop trash-cli blueman upower iw ffmpeg libxcb-xinerama0-dev libxcb-randr0-dev libxft-dev libx11-dev libx11-xcb-dev bc
