#!/bin/sh

sudo nala install -y ninja-build gettext cmake curl build-essential python3.12-venv
git clone https://github.com/neovim/neovim $HOME/Github/neovim/
cd $HOME/Github/neovim/
git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install &
sudo npm i -g eslint
cd $OLDPWD
