format = """
$directory\
$git_branch\
$character\
"""
add_newline = true

[directory]
style = "fg:bold blue"
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = "[$branch]($style) "
style = "red"

[character]
success_symbol = '[\$](fg:white)'
error_symbol = '[\$](fg:white)'
