#! /bin/sh

xrandr --output $(xrandr | grep ' connected' | awk '{print $1}' | head -n 1) --scale 0.75x0.75 &
xmodmap ~/.Xmodmap &
pkill -x lemonbar
lemonbar-panel &
pkill -x redshift
redshift -x && redshift -P -l 24.47:88.07 -t 4800:4300 &
pgrep -x sxhkd >/dev/null || sxhkd && pkill -USR1 -x sxhkd &
feh --no-fehbg --bg-fill $HOME/Pictures/aesthetic-anime.jpg &
xsetroot -cursor_name left_ptr &
xset s off -dpms &
dunst &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.5
bspc config pointer_modifier mod1
bspc config normal_border_color "#7F8487"
bspc config active_border_color "#99bbaa"
bspc config focused_border_color "#99bbaa"

bspc rule -a "*:Toolkit:Picture-in-Picture" state=floating sticky=on focus=on rectangle=400x200+1015+60
bspc rule -a pavucontrol state=floating rectangle=700x400+0+0 center=true
bspc rule -a Sxiv state=floating rectangle=800x500+0+0 center=true
bspc rule -a mpv state=floating rectangle=400x400+1015+60
