#!/usr/bin/env bash

chosen=$(printf "⏻\n\n󰗽" | rofi -dmenu -i -cycle -hover-select -me-select-entry '' -me-accept-entry MousePrimary -theme-str '
mainbox {
    children: ["listview"];
}
window {
    width: 20%;                     
}
listview{
    lines: 3;
}
element {
    padding: 30px;
    cursor: pointer;
}
element-text {
    font: "nerd 50";
    vertical-align: 0.5;
    horizontal-align: 0.5;
}
')

case "$chosen" in
"⏻") poweroff ;;
"") reboot ;;
"󰗽") pkill x ;;
*) exit 1 ;;
esac
