#!/bin/sh
main_dir="$HOME/dotfiles"
config_dir="$main_dir/.config"

# Create necessary directories if they don't exist
mkdir -p "$main_dir/.config" "$main_dir/etc/X11/xorg.conf.d" "$main_dir/etc/ly" "$main_dir/Pictures"

# Function to copy single files if they exist
copy_file() {
    [ -f "$1" ] && sudo cp "$1" "$2" || echo "$1 does not exist."
}

# Function to copy directories with rsync if they exist
copy_dir() {
    [ -d "$1" ] && sudo rsync -av --delete-before "$1" "$2" || echo "$1 does not exist."
}

# Copy individual configuration files
copy_file "$HOME/.librewolf/librewolf.overrides.cfg" "$main_dir/.librewolf/"
copy_file "$HOME/.config/starship.toml" "$main_dir/.config/"
copy_file "$HOME/.fonts.conf" "$main_dir/"
copy_file "$HOME/.bashrc" "$main_dir/"
copy_file "$HOME/.Xmodmap" "$main_dir/"
copy_file "$HOME/.Xresources" "$main_dir/"
copy_file "$HOME/.config/gtk-3.0/settings.ini" "$main_dir/.config/gtk-3.0/"
copy_file "/etc/X11/xorg.conf.d/99-input.conf" "$main_dir/etc/X11/xorg.conf.d/"
copy_file "/etc/ly/config.ini" "$main_dir/etc/ly/"

# Copy configuration directories
copy_dir "$HOME/.local/bin/" "$main_dir/bin/"
copy_dir "$HOME/.config/lemonbar/" "$main_dir/.config/lemonbar/"
copy_dir "$HOME/.config/lf/" "$main_dir/.config/lf/"
copy_dir "$HOME/.config/dunst/" "$main_dir/.config/dunst/"
copy_dir "$HOME/.config/nvim/" "$main_dir/.config/nvim/"
copy_dir "$HOME/.config/mpv/" "$main_dir/.config/mpv/"
copy_dir "$HOME/.config/sxiv/" "$main_dir/.config/sxiv/"
copy_dir "$HOME/.config/bspwm/" "$main_dir/.config/bspwm/"
copy_dir "$HOME/.config/sxhkd/" "$main_dir/.config/sxhkd/"
copy_dir "$HOME/.config/htop/" "$main_dir/.config/htop/"
copy_dir "$HOME/.config/mpd/" "$main_dir/.config/mpd/"
copy_dir "$HOME/.config/ncmpcpp/" "$main_dir/.config/ncmpcpp/"
copy_dir "$HOME/.config/tmux/" "$main_dir/.config/tmux/"
