[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding = { x = 10, y = 0 }
dynamic_padding = true

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold Italic" }
size = 16.00

[general]
import = [
"~/.config/alacritty/colortheme.toml"
]
