[colors.primary]
background = '#191919'
foreground = '#DBDBDB'

[colors.search.matches]
foreground = "CellBackground"
background = "CellForeground"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.footer_bar]
background = '#191919'
foreground = '#DBDBDB'

# Normal colors
[colors.normal]
black   = '#191919'
red     = '#e67e80'
green   = '#99bbaa'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#E6B2BA'
cyan    = '#81A1C1'
white   = '#DBDBDB'

# Bright colors
[colors.bright]
black   = '#7F8487'
red     = '#ab4642'
green   = '#99bbaa'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#E6B2BA'
cyan    = '#81A1C1'
white   = '#DBDBDB'
