sudo nala remove --purge redshift-gtk -y
sudo nala remove --purge seahorse -y
sudo nala remove --purge sticky -y
sudo nala remove --purge gnome-calculator -y
sudo nala remove --purge simple-scan -y
sudo nala remove --purge hexchat pix -y
sudo nala remove --purge rhythmbox -y
sudo nala remove --purge webapp-manager -y
sudo nala remove --purge xfce4-terminal -y
sudo nala remove --purge thunderbird -y
sudo nala remove thunderbird-locale-en -y
sudo nala remove thunderbird-locale-en-us -y
sudo nala remove --purge transmission-gtk -y
sudo nala remove --purge xserver-xorg-video-intel -y
sudo nala remove --purge geoclue-2.0 -y
sudo nala remove --purge hypnotix -y
sudo nala remove --purge timeshift -y
sudo nala remove --purge autojump -y
sudo nala remove --purge xfce4-notifyd -y
sudo nala remove --purge gnome-keyring -y
sudo nala remove --purge gnome-keyring-pkcs11 -y
sudo nala remove --purge evolution-data-server -y
sudo nala remove --purge evolution-data-server-common -y
sudo nala remove --purge ibebackend-1.2-10 -y
sudo nala remove --purge libebook-1.2-20 -y
sudo nala remove --purge libebook-contacts-1.2-3 -y
sudo nala remove --purge libecal-2.0-1 -y
sudo nala remove --purge libedata-book-1.2-26 -y
sudo nala remove --purge libedata-cal-2.0-1 -y
sudo nala remove --purge libedataserver-1.2-26 -y
sudo nala remove --purge libedataserverui-1.2-3 -y
sudo nala remove --purge xfce4-dict -y
sudo nala remove --purge libreoffice-calc -y
sudo nala remove --purge libreoffice-math -y
sudo nala remove --purge libreoffice-base -y
sudo nala remove --purge mintbackup -y
sudo nala remove --purge neofetch -y
sudo nala remove --purge nip2 -y
sudo nala remove --purge i3lock -y
sudo nala remove --purge xss-lock -y
sudo nala remove --purge catfish -y
sudo nala remove --purge onboard -y
sudo nala remove --purge thunar -y
sudo nala remove --purge xfce4-screenshooter -y
sudo nala remove --purge baobab -y
sudo nala remove --purge mintupdate -y
sudo nala remove --purge xviewer -y
sudo nala remove --purge gnome-online-accounts -y
sudo nala remove --purge xreader -y
sudo nala remove --purge celluloid -y
sudo nala remove --purge firefox -y
