#!/bin/sh

# creating nessesery folders
mkdir -p $HOME/Github/ $HOME/Projects/

# installing generic packages
sudo pacman -Syu --needed --noconfirm dunst alacritty ripgrep xclip rofi bspwm sxhkd feh lf bat mediainfo catdoc docx2txt odt2txt ffmpegthumbnailer imagemagick mpv sxiv zathura zathura-pdf-poppler file-roller redshift tmux scrot brightnessctl zoxide fd htop trash-cli bluez bluez-utils blueman upower iw ffmpeg bc util-linux lftp ncmpcpp mpd starship rsync xorg ueberzug unzip zip nodejs npm nvim pavucontrol fontconfig base-devel git networkmanager perl-file-mimeinfo fzf adw-gtk-theme papirus-icon-theme thunar gnome-disk-utility terminus-font

# Installing yay
git clone https://aur.archlinux.org/yay.git $HOME/Github/yay
cd $HOME/Github/yay/
makepkg -si
cd $OLDPWD

yay -Syu --needed --noconfirm ani-cli librewolf-bin lemonbar-xft-git bibata-cursor-theme vesktop-bin
# /spotdl

#tpm
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

#fonts
mkdir -p ~/.local/share/fonts
cd ~/.local/share/fonts && rm -rf ~/.local/share/fonts/*
curl -fLO https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaMono.zip
unzip CascadiaMono.zip
rm CascadiaMono.zip
cd $OLDPWD

# Notes :
# if using vesktop do turn on nodevtoolsswarning in plugins to not signout everytime.
