#!/bin/sh

git clone https://github.com/spotDL/spotify-downloader $HOME/Github/spotify-downloader
cd $HOME/Github/spotify-downloader
sudo nala install -y python3-poetry
poetry install
poetry run python3 scripts/build.py
sudo cp dist/* -r /usr/bin/spotdl
sudo nala purge -y python3-poetry
cd $OLDPWD
