#!/bin/bash

# Get the window IDs of the removed nodes
node_ids="$(bspc query -M -m) $(bspc query -D -d) $(bspc query -N -n)"

# Kill the node
bspc node -k

# Simulate a custom event with window IDs
echo "node_remove $node_ids" >>/tmp/custom_bspwm_events
