#! /bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=35
PANEL_FONT="CaskaydiaMono Nerd Font:pixelsize=16"
PANEL_WM_NAME=bspwm_panel
export PANEL_FIFO PANEL_HEIGHT PANEL_FONT PANEL_WM_NAME

if xdo id -a "$PANEL_WM_NAME" >/dev/null; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# Monitor battery status
while
    battery=$(cat /sys/class/power_supply/BAT1/capacity) # Adjust if necessary
    status=$(cat /sys/class/power_supply/BAT1/status)    # Charging or Discharging
    echo "B${battery}% (${status})"
do
    sleep 30 # Update every 30 seconds
done >"$PANEL_FIFO" &

# Monitor the date and time
while date +"D%d %a, %H:%M"; do
    sleep 30
done >"$PANEL_FIFO" &
bspc subscribe report >"$PANEL_FIFO" &

. $HOME/.config/lemonbar/panel_colors

$HOME/.config/lemonbar/panel_bar <"$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
